<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <PackageId>WhatIsHeDoing.DomainModels </PackageId>
    <PackageVersion>8.0.0</PackageVersion>
    <Authors>WhatIsHeDoing</Authors>
    <Description>A library of domain models for .NET.</Description>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>Upgrading latest Core package</PackageReleaseNotes>
    <Copyright>
    </Copyright>
    <PackageTags>domain models</PackageTags>
    <PackageLicenseExpression>Unlicense</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/WhatIsHeDoing/WhatIsHeDoing.DomainModels</PackageProjectUrl>
    <Version>8.0.0</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Company />
    <RepositoryUrl>https://github.com/WhatIsHeDoing/WhatIsHeDoing.DomainModels</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IconUrl>https://darrenhickling.com/static/favicons/apple-touch-icon-60x60.png</IconUrl>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <PropertyGroup>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <CodeAnalysisRuleSet>..\WhatIsHeDoing.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="RoslynSecurityGuard" />
    <PackageReference Include="StyleCop.Analyzers" />
    <PackageReference Include="WhatIsHeDoing.Core" />
  </ItemGroup>
  <!-- https://devblogs.microsoft.com/dotnet/add-a-readme-to-your-nuget-package/ -->
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>