language: csharp
solution: WhatIsHeDoing.DomainModels.sln
mono: none
dotnet: 2.2.401
install:
  - dotnet restore
script:
  - dotnet build --configuration Release
  - dotnet test WhatIsHeDoing.DomainModels.Tests/WhatIsHeDoing.DomainModels.Tests.csproj
