version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
environment:
  ApiKey:
    secure: 0vvD9xkaKen4fUz/3PIi0hbKx6Nyggnvlv8/EOyMtzG/t9T4h/3pdJQJQGa9Tf1z
build_script:
- ps: >-
    dotnet restore

    dotnet build --configuration Release
test_script:
- ps: dotnet test --configuration Release .\WhatIsHeDoing.DomainModels.Tests\WhatIsHeDoing.DomainModels.Tests.csproj
deploy_script:
- ps: nuget push WhatIsHeDoing.DomainModels\bin\Release\WhatIsHeDoing.DomainModels.*.nupkg -ApiKey $env:ApiKey -Source https://www.nuget.org/api/v2/package
