version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
environment:
  ApiKey:
    secure: 0vvD9xkaKen4fUz/3PIi0hbKx6Nyggnvlv8/EOyMtzG/t9T4h/3pdJQJQGa9Tf1z
build_script:
- ps: >-
    dotnet restore

    dotnet build --configuration Release
test_script:
- ps: dotnet test --configuration Release .\WhatIsHeDoing.DomainModels.Tests\WhatIsHeDoing.DomainModels.Tests.csproj
artifacts:
  - path: 'WhatIsHeDoing.DomainModels\bin\Release\WhatIsHeDoing.DomainModels.*.nupkg'
    name: WhatIsHeDoing.DomainModels NuGet package
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: 0vvD9xkaKen4fUz/3PIi0hbKx6Nyggnvlv8/EOyMtzG/t9T4h/3pdJQJQGa9Tf1z
  skip_symbols: false
  artifact: /.*\.nupkg/
