name: build

on:
    push:
        branches:
            - live
        tags:
            - "v*"

    pull_request:
        branches:
            - live

    workflow_dispatch:

jobs:
    build:
        if: github.actor != 'dependabot[bot]'
        runs-on: ubuntu-24.04
        steps:
            - name: Check out the repo
              uses: actions/checkout@v7.0.0
              with:
                  fetch-depth: 0

            - name: Set up .NET
              uses: actions/setup-dotnet@v5.2.0
              with:
                  dotnet-version: "10.0.x"

            - name: Cache NuGet packages
              uses: actions/cache@v5.0.5
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props', '**/*.csproj') }}
                  restore-keys: ${{ runner.os }}-nuget-

            - name: Restore dependencies
              run: dotnet restore --locked-mode && dotnet tool restore

            - name: Run the build
              run: dotnet build --configuration Release --no-restore

            - name: Check code formatting
              run: dotnet format style --verify-no-changes

            - name: Run tests with coverage
              run: dotnet tool run dotnet-coverage collect "dotnet test --no-restore" --output ./coverage.xml --output-format cobertura

            # - name: Upload coverage to Codecov
            #   uses: codecov/codecov-action@v5
            #   with:
            #       files: ./coverage.xml
            #       token: ${{ secrets.CODECOV_TOKEN }}

            - name: Pack the project
              run: dotnet pack --configuration Release --no-restore --output ${{ github.workspace }}/nuget

            - name: Publish the NuGet package
              if: startsWith(github.ref, 'refs/tags/')
              run: dotnet nuget push ${{ github.workspace }}/nuget/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
